all : ios-armv7-release

metadata_confDeps := ../EmuFramework/metadata/conf.mk

include $(IMAGINE_PATH)/make/shortcut/webos.mk

include $(IMAGINE_PATH)/make/shortcut/android.mk

include $(IMAGINE_PATH)/make/shortcut/iOS.mk
